name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_forms: ^2.1.0
  angular_components: ^0.13.0+1

dev_dependencies:
  build_runner: ^1.5.1
  build_web_compilers: ^2.1.0
